/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.mrpaulblack.tron;

import org.junit.Test;
import static org.junit.Assert.*;

public class ClientTest {
    @Test public void serverHasAGreeting() {
        Client classUnderTest = new Client();
        assertNotNull("Client should have a greeting", classUnderTest.getGreeting());
    }
}
